name: auto-deploy

on: [push]

jobs:
  autodeploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Install pack CLI via the official buildpack Action https://github.com/buildpacks/github-actions#setup-pack-cli-action
        uses: buildpacks/github-actions/setup-pack@v5.0.0

      # Caching Paketo Build see https://stackoverflow.com/a/66598693/4964553
      # BP_OCI_SOURCE as --env creates the GitHub Container Registry <-> Repository link (https://paketo.io/docs/buildpacks/configuration/#applying-custom-labels)
      # BP_JVM_VERSION 17, because we use Java 17 inside our Gradle build but Paketo defaults to 11
      # Explicitly defining the java-native-image buildpack as described here https://paketo.io/docs/howto/java/#configure-the-graalvm-version to pin the GraalVM version (5.12.0 = GraalVM 21.3)
      # Files specifies within BP_NATIVE_IMAGE_BUILD_ARGUMENTS have to be absolute path related to the workspace - they have to be prefixed with "/workspace/"
      # https://github.com/paketo-buildpacks/java-native-image
      - name: Build app with pack CLI & publish to GitHub Container Registry
        run: |
          pack build ghcr.io/little-fish/gcunicorn:latest \
            --builder paketobuildpacks/builder:tiny \
            --buildpack paketo-buildpacks/java-native-image@8.7.1 \
            --path . \
            --env "BP_JVM_VERSION=17" \
            --env "BP_GRADLE_BUILD_ARGUMENTS=--no-daemon :webapp:signedBootJar" \
            --env "BP_GRADLE_BUILT_ARTIFACT=webapp/build/libs/*signed.jar" \
            --env "BP_INCLUDE_FILES=webapp/src/graalvm/config/v1.1.0/*.json" \
            --env "BP_NATIVE_IMAGE=true" \
            --env "BP_NATIVE_IMAGE_BUILD_ARGUMENTS=-H:ReflectionConfigurationFiles=/workspace/webapp/src/graalvm/config/v1.1.0/reflect-config.json -H:ResourceConfigurationFiles=/workspace/webapp/src/graalvm/config/v1.1.0/resource-config.json" \
            --cache-image ghcr.io/little-fish/gcunicorn-cache-image:latest \
            --publish
      - name: Install flyctl via https://github.com/superfly/flyctl-actions
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy our Spring Boot app to fly.io
        run: flyctl deploy --image ghcr.io/czbabi/gcunicorn:latest